#!/bin/sh

name=${0##*/}
url=https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$name

cat <<EOF
<?xml version="1.0" ?>

<rdf:RDF
  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  xmlns="http://purl.org/rss/1.0/">

<channel>
<title>$name</title>
<link>$url</link>
<description></description>
</channel>
EOF

curl -s $url | awk '
match($0, /pkgver=(.*)/, m) {
	print "";
	print "<item>";
	print "<title>" m[1] "</title>";
	print "<link></link>";
	print "<description></description>";
	print "</item>";
	exit;
}'

# End of file
